-- Source: KAN-25
-- Target: d_customer
-- Branches: 1
-- Fields: 169
-- Unresolved: 134
-- Pipeline Run: pipeline-KAN-25
-- Validation: WARNINGS

(select
  concat('msd_qad_',lower(ad_mstr.ad_domain))||'|'||ad_mstr.ad_addr as cust_key,
  concat('msd_qad_',lower(ad_mstr.ad_domain))||'|'||ad_mstr.ad_addr as src_sys_cd,
  cast(CM.cm_addr as string) as cust_id,
  cast(ad_mstr.ad_name as string) as cust_nm,
  cast(ad_mstr.ad_name as string) as cust_nm_en,
  cast(ad_mstr.ad_type as string) as cust_type_cd,
  cast(ad_mstr.ad_type as string) as cust_type_nm,
  cast(null as string) as active_flg,
  cast(null as string) as parent_cust_id,
  cast(null as string) as parent_cust_nm,
  cast(null as string) as naics_cd,
  cast(null as string) as naics_nm,
  cast(null as string) as sic_cd,
  cast(null as string) as sic_nm,
  cast(null as string) as gbl_govt_id,
  cast(null as string) as gbl_loc_nbr,
  cast(null as string) as dnb_duns_nm,
  cast(null as string) as alt_payer_cust_id,
  cast(null as decimal(38,6)) as annl_sls_amt,
  cast(null as string) as central_bill_block_cd,
  cast(null as string) as central_bill_block_nm,
  cast(null as string) as central_delvr_block_cd,
  cast(null as string) as central_delvr_block_nm,
  cast(null as string) as central_ord_block_cd,
  cast(null as string) as central_ord_block_nm,
  cast(null as string) as cust_acct_grp_cd,
  cast(null as string) as cust_acct_grp_nm,
  cast(null as string) as cust_class_cd,
  cast(null as string) as cust_class_nm,
  cast(CM.cm_curr as string) as curncy_cd,
  cast(CURR.currencydescription as string) as curncy_nm,
  cast(null as string) as indy_cd,
  cast(null as string) as indy_nm,
  cast(null as string) as intl_loc_nbr_check_digit,
  cast(ad_mstr.ad_lang as string) as lang_cd,
  cast(null as string) as lang_iso_cd,
  cast(null as string) as lang_nm,
  cast(null as string) as lgl_stat_cd,
  cast(null as string) as lgl_stat_nm,
  cast(null as string) as rgn_mkt,
  cast(null as string) as sls_since_yr,
  cast(ad_mstr.ad_sort as string) as sort_field,
  cast(ad_mstr.ad_tax_usage as string) as tax_juris_cd,
  cast(null as string) as tax_juris_nm,
  cast(null as string) as teletex_nbr,
  cast(null as string) as telex_nbr,
  cast(null as string) as title,
  cast(null as string) as transp_zone_cd,
  cast(null as string) as transp_zone_nm,
  cast(null as string) as trading_prtnr_co_cd,
  cast(null as string) as url,
  cast(null as string) as unload_point_flg,
  cast(ad_mstr.ad_vat_reg as string) as vat_regstr_nbr,
  cast(null as string) as central_del_block_flg,
  cast(null as string) as central_del_flg,
  cast(null as string) as central_post_block_flg,
  cast(null as string) as central_sls_block_flg,
  cast(null as string) as cmptr_flg,
  cast(null as string) as natural_pers_flg,
  cast(null as string) as one_time_cust_flg,
  cast(null as string) as sls_prtnr_flg,
  cast(null as string) as sls_prospect_flg,
  cast(concat('msd_qad_',lower(ad_mstr.ad_domain))||'|'||ad_mstr.ad_address_id as int) as addr_key,
  cast(ad_mstr.ad_line2 as string) as street_line,
  cast(ad_mstr.ad_zip as string) as pstl_cd,
  cast(ad_mstr.ad_city as string) as city,
  cast(null as string) as city_coord,
  cast(null as string) as po_box,
  cast(null as string) as po_box_pstl_cd,
  cast(null as string) as district,
  cast(ad_mstr.ad_state as string) as st_prov_cd,
  cast(null as string) as st_prov_nm,
  cast(ad_mstr.ad_ctry as string) as cntry_cd,
  cast(ad_mstr.ad_country as string) as cntry_nm,
  cast(ad_mstr.ad_fax as string) as fax_nbr,
  cast(null as string) as trading_prtnr_co_nm,
  cast(null as int) as prim_contact_key,
  cast(null as string) as dnb_duns_nbr,
  cast(ad_mstr.ad_line1 as string) as addr_nm_line2,
  cast(ad_mstr.ad_line2 as string) as addr_nm_line3,
  cast(ad_mstr.ad_line3 as string) as addr_nm_line4,
  cast(null as string) as cust_cond_grp_cd1,
  cast(null as string) as cust_cond_grp_cd2,
  cast(null as string) as cust_cond_grp_nm1,
  cast(null as string) as cust_cond_grp_nm2,
  cast(ad_mstr.ad_email as string) as cust_email_addr_txt,
  cast(null as string) as cust_rept_hier_base,
  cast(null as int) as dw_src_key,
  cast(null as string) as indy_cd1,
  cast(null as string) as indy_cd2,
  cast(null as string) as indy_nm1,
  cast(null as string) as indy_nm2,
  cast(null as string) as intl_loc_nbr1,
  cast(null as string) as intl_loc_nbr2,
  cast(ad_mstr.ad_phone as string) as phn_nbr1,
  cast(ad_mstr.ad_phone2 as string) as phn_nbr2,
  cast(null as string) as search_mcode1,
  cast(null as string) as search_mcode2,
  cast(null as string) as search_mcode3,
  cast(null as string) as sply_center_cd,
  cast(null as string) as sply_center_flg,
  cast(null as string) as sply_center_nm,
  cast(ad_mstr.ad_pst_id as string) as tax_nbr1,
  cast(null as string) as tax_nbr2,
  cast(null as string) as tax_nbr3,
  cast(null as string) as src_crt_by,
  cast(ad_mstr.ad_date as string) as src_crt_ts,
  cast(ad_mstr.ad_userid as string) as src_updt_by,
  cast(CM.cm_mod_date as string) as src_updt_ts,
  current_timestamp as rec_crt_ts,
  current_timestamp as rec_updt_ts,
  cast(null as string) as stock_ticker_cd,
  cast(null as string) as cdw_cust_key,
  cast(null as string) as dw_cust_key,
  cast(null as string) as addr_phn_nbr,
  cast(ad_mstr.ad_fax2 as string) as addr_fax_nbr,
  cast(null as string) as sls_chnl_cd,
  cast(null as string) as sls_terr_cd,
  cast(null as string) as sls_rep_cust_key,
  cast(null as string) as addr_type_cd,
  cast(null as string) as hfm_entity_key,
  cast(null as string) as hfm_entity_cd,
  concat('msd_qad_',lower(ad_mstr.ad_domain))||'|'||DCH.cntry_hier_key as deflt_delvr_cntry_key,
  cast(ad_mstr.ad_ctry as string) as deflt_delvr_cntry_cd,
  cast(null as string) as trade_chnl_cd,
  case when ad_mstr.ad_addr like 'Z%' OR ad_mstr.ad_addr like 'TM%' then 'IC' else '3rd' end as inter_co_cd,
  cast(null as string) as county,
  cast(null as string) as temporary flag,
  cast(null as string) as Bank Acct 1,
  cast(null as string) as CoC Number,
  cast(null as string) as Tax ID - Federal,
  cast(null as string) as Tax Type,
  cast(null as string) as Tax Class Code,
  cast(null as string) as taxable flag,
  cast(null as string) as tax in flag,
  cast(null as string) as Netting Logic,
  cast(null as string) as Trading Prtnr Interface ID,
  cast(null as string) as EDI Control,
  cast(null as string) as Time Zone,
  cast(null as string) as Trading Prtnr EDI ID,
  cast(null as string) as Barcode Label Print Program,
  cast(null as string) as Barcode Validation Program,
  cast(null as string) as Calendar,
  cast(null as string) as EDI Standard,
  cast(null as string) as EDI Standard Level,
  cast(null as string) as Trd Partner Location Code,
  cast(null as string) as Tax Zone,
  cast(null as string) as Tax ID - Misc 1,
  cast(null as string) as Tax ID - Misc 2,
  cast(null as string) as Tax ID - Misc 3,
  cast(null as string) as Week Offset,
  cast(null as string) as Invoices Via,
  cast(null as string) as Schedules Via,
  cast(null as string) as Purchase Orders Via,
  cast(null as string) as ASN Default Data,
  cast(null as string) as IntraStat Division,
  cast(null as string) as Tax Report Flag,
  cast(null as string) as Name Control,
  cast(null as string) as Last Filing Flag,
  cast(null as string) as Priority,
  cast(null as string) as Route,
  cast(null as string) as Load Sequence,
  cast(null as string) as Pick By Date,
  cast(null as string) as Profile,
  cast(null as string) as tac In City Flag,
  cast(null as string) as Non-Sales Price List,
  cast(null as string) as Business Relation,
  cast(null as string) as Alternate UM,
  cast(null as string) as City Code
from cm_mstr CM
  left join ad_mstr  on CM.cm_addr=ad_mstr.ad_addr and lower(cm.cm_domain)=lower(ad_mstr.ad_domain)
  left join currency CURR on CURR.currencycode=CM.cm_curr
  inner join d_cntry_hier DCH on UPPER(DCH.cntry_nm)=ad_mstr.ad_country
)