-- Source: KAN-24
-- Target: f_sls_invc
-- Branches: 1
-- Fields: 368
-- Unresolved: 320
-- Pipeline Run: pipeline-KAN-24
-- Validation: WARNINGS

(select
  cast(null as decimal(38,0)) as accntng_setlmt_prd_start_dt_key,
  cast(null as string) as accntng_type_cd,
  cast(null as string) as accntng_type_nm,
  cast(null as string) as acct_assgn_grp_cd,
  cast(null as string) as acct_assgn_grp_nm,
  cast(null as string) as active_credit_flg,
  cast(null as string) as adj_sched_cd,
  cast(null as string) as adj_sched_nm,
  cast(null as string) as batch_nbr,
  cast(null as string) as batch_split_high_lvl_nbr,
  cast(BusinessRelation.businessrelationcode as string) as bill_to_addr_cd,
  cast(null as string) as bill_to_addr_key,
  cast(null as string) as bill_to_bus_area_cd,
  cast(Debtor.debtorcode as string) as bill_to_cust_id,
  concat("msd_qad_",lower(company.companydomain))||'|'||Debtor.debtorcode as bill_to_cust_key,
  cast(null as string) as bill_to_cust_nm,
  cast(null as string) as bill_to_cust_sls_key,
  cast(null as string) as bill_to_distrb_chnl_cd,
  cast(null as string) as bill_to_sls_org_cd,
  cast(null as string) as bom_high_lvl_nbr,
  cast(null as string) as bu_cd,
  cast(null as string) as bus_area_cd,
  cast(null as string) as bus_area_nm,
  cast(null as string) as bus_grp_cd,
  cast(null as string) as carry_out_prc_flg,
  cast(null as double) as cash_disc_elg_lcur_amt,
  cast(null as string) as ccg_gc_vndr_nbr,
  cast(null as string) as cfop_cd,
  cast(null as string) as cfop_nm,
  cast(null as double) as cntrbtn_cost_lcur_amt,
  cast(null as string) as cntry_alpha2_cd,
  cast(null as string) as cntry_hier_key,
  cast(null as string) as cntry_nm,
  cast(C.companycode as string) as co_cd,
  concat("msd_qad_",lower(company.companydomain))||'|'||company.companycode as co_key,
  cast(Dinvoice.dinvoiceexchangerate as string) as co_lcur_dly_rt,
  cast(C.companydescription as string) as co_nm,
  cast(null as string) as co_usd_curncy_mth_rt_key,
  cast(null as string) as cofins_tax_law_cd,
  cast(null as string) as cofins_tax_law_nm,
  cast(null as string) as commssn_grp_cd,
  cast(null as string) as commssn_grp_nm,
  cast(null as string) as cond_updt_flg,
  cast(null as string) as contact_key,
  cast(IDH.idh_cc as string) as cost_center_cd,
  cast(IDH.idh_std_cost as double) as cost_lcur_amt,
  cast(null as string) as credit_acct_cust_id,
  cast(null as string) as credit_acct_cust_key,
  cast(null as string) as credit_acct_cust_nm,
  cast(null as string) as cur_ord_stat_cd,
  cast(null as string) as cur_ord_stat_nm,
  cast(null as string) as cust_key,
  cast(null as string) as dealer_cust_id,
  cast(null as string) as dealer_cust_key,
  cast(null as string) as dealer_cust_nm,
  cast(null as string) as delvr_time_bucket_cd,
  cast(null as string) as delvr_time_bucket_nm,
  cast(null as string) as depart_cntry_hier_key,
  cast(null as string) as depart_cntry_nm,
  cast(null as string) as derived_prod_key,
  cast(null as string) as derived_sku,
  cast(null as string) as derived_sku_nm,
  cast(null as double) as disc_amt,
  cast(null as string) as distrb_chnl_cd,
  cast(null as string) as distrb_chnl_nm,
  cast(null as string) as div_grp_cd,
  cast(null as string) as dw_sls_invc_key,
  DInvoice.invoice_date||'|'||Debtor.debtorcode||'|'||CASE 
        WHEN ih.ih_fsm_type = 'SC' 
             AND idh.idh_for IS NOT NULL 
             AND TRIM(idh.idh_for) <> ''
        THEN idh.idh_for 
        ELSE idh.idh_part 
    END as dw_src_cd,
  cast(dinvoice.dinvoiceshiptocode as string) as end_user_cust_id,
  cast(null as string) as end_user_cust_key,
  cast(null as string) as end_user_cust_nm,
  cast(null as string) as enter_sku,
  cast(null as string) as foreign_trade_exch_rt,
  cast(null as string) as gbl_rgn_cd,
  cast(null as string) as gbl_rgn_nm,
  cast(null as string) as gbl_sub_rgn_2_cd,
  cast(null as string) as gbl_sub_rgn_2_nm,
  cast(null as string) as gbl_sub_rgn_3_cd,
  cast(null as string) as gbl_sub_rgn_3_nm,
  cast(null as string) as gbl_sub_rgn_cd,
  cast(null as string) as gbl_sub_rgn_nm,
  cast(null as string) as genrl_incomplt_flg,
  cast(IDH.idh_acct as string) as gl_acct_id,
  cast(null as string) as gl_acct_key,
  cast(null as string) as gl_class_cd,
  cast(null as double) as gross_val_lcur_amt,
  cast(null as string) as grp_purch_org_cd,
  cast(null as string) as grp_purch_org_nm,
  cast(null as string) as guarnt_factor,
  cast(null as string) as hdr_accrual_invc_flg,
  cast(null as string) as hdr_acct_assgn_grp_cd,
  cast(null as string) as hdr_acct_assgn_grp_nm,
  cast(null as string) as hdr_assgn_nbr,
  cast(null as string) as hdr_cancel_flg,
  cast(null as string) as hdr_cancel_invc_nbr,
  cast(null as string) as hdr_combine_criteria_nbr,
  cast(null as string) as hdr_cond_nbr,
  cast(null as string) as hdr_credit_cntrl_area_cd,
  cast(null as string) as hdr_credit_cntrl_area_curncy_cd,
  cast(null as string) as hdr_credit_cntrl_area_curncy_nm,
  cast(null as string) as hdr_credit_cntrl_area_nm,
  cast(null as string) as hdr_credit_exch_rt,
  cast(IH.ih_curr as string) as hdr_curncy_cd,
  cast(null as string) as hdr_cust_grp_cd,
  cast(null as string) as hdr_cust_grp_nm,
  cast(Dinvoice.DInvoicePurchaseOrder as string) as hdr_cust_po_nbr,
  cast(null as string) as hdr_cust_prc_grp_cd,
  cast(null as string) as hdr_cust_prc_grp_nm,
  cast(null as string) as hdr_cust_tax_calss_1_cd,
  cast(null as string) as hdr_cust_tax_calss_2_cd,
  cast(null as string) as hdr_cust_tax_calss_3_cd,
  cast(null as string) as hdr_cust_tax_calss_4_cd,
  cast(Dinvoice.DInvoicePostingDate as timestamp) as hdr_entry_ts,
  cast(null as string) as hdr_exch_rt_type,
  cast(null as string) as hdr_export_type_cd,
  cast(null as string) as hdr_fin_exch_rt,
  cast(null as string) as hdr_foreign_trade_nbr,
  cast(null as string) as hdr_incoterm_1_cd,
  cast(null as string) as hdr_incoterm_2_cd,
  cast(null as string) as hdr_invc_cat_cd,
  cast(null as string) as hdr_invc_cat_nm,
  cast(null as string) as hdr_invc_list_invc_type_cd,
  cast(null as string) as hdr_invc_list_invc_type_nm,
  cast(null as string) as hdr_invc_stat_cd,
  cast(null as string) as hdr_invc_stat_nm,
  cast(DI.dinvoicetype as string) as hdr_invc_type_cd,
  cast(null as string) as hdr_invc_type_nm,
  cast(null as double) as hdr_lcur_amt,
  cast(null as string) as hdr_ord_cat_cd,
  cast(null as string) as hdr_ord_cat_nm,
  cast(null as string) as hdr_paymt_plan_type_cd,
  cast(null as string) as hdr_paymt_plan_type_nm,
  cast(null as string) as hdr_paymt_ref_nbr,
  cast(null as string) as hdr_paymt_term_cd,
  cast(null as string) as hdr_paymt_term_nm,
  cast(null as string) as hdr_prc_hier_type_cd,
  cast(null as string) as hdr_prc_hier_type_nm,
  cast(null as string) as hdr_prc_list_type_cd,
  cast(null as string) as hdr_prc_list_type_nm,
  cast(null as string) as hdr_prc_proc_cd,
  cast(null as string) as hdr_prc_proc_nm,
  cast(null as string) as hdr_set_exch_rt_flg,
  cast(null as string) as hdr_ship_cond_cd,
  cast(null as string) as hdr_ship_cond_nm,
  cast(null as string) as hdr_sls_district_cd,
  cast(null as string) as hdr_sls_district_nm,
  cast(null as string) as hdr_sls_ord_po_nbr,
  cast(null as string) as hdr_sls_tax_cntry_hier_key,
  cast(null as string) as hdr_sls_tax_orig_cd,
  cast(null as string) as hdr_statis_curncy_cd,
  cast(null as string) as hdr_statis_curncy_nm,
  cast(null as string) as hdr_statis_updt_grp_cd,
  cast(null as string) as hdr_tax_dept_cntry_hier_key,
  cast(null as double) as hdr_tax_lcur_amt,
  cast(null as string) as hdr_trade_prtnr_co_cd,
  cast(null as string) as hdr_trade_prtnr_co_nm,
  cast(null as string) as hdr_vat_regstr_nbr,
  cast(null as string) as hfm_entity_cd,
  cast(null as string) as hfm_entity_key,
  cast(null as string) as hfm_entity_nm,
  cast(null as string) as hold_cd,
  cast(null as string) as hold_nm,
  cast(null as string) as icms_tax_law_cd,
  cast(null as string) as icms_tax_law_nm,
  cast(null as string) as intrnl_object_nbr,
  cast(DI.dinvoicedate as decimal(38,0)) as invc_dt_key,
  cast(null as decimal(38,0)) as invc_hdr_list_invc_dt_key,
  cast(null as decimal(38,0)) as invc_hdr_transl_dt_key,
  cast(null as string) as invc_hdr_usd_curncy_mth_rt_key,
  cast(Dinvoice.DInvoiceCreationDate as timestamp) as invc_line_entry_ts,
  cast(null as string) as invc_line_type_cd,
  cast(null as string) as invc_plan_cd,
  cast(null as string) as invc_plan_nm,
  cast(null as string) as invc_plan_rule,
  cast(IDH.Idh_price as double) as invc_prc_per_unit_amt,
  cast(IDH.idh_qty_inv as double) as invc_qty,
  cast(null as string) as ipi_tax_law_cd,
  cast(null as string) as ipi_tax_law_nm,
  cast(null as string) as item_credit_prc_1,
  cast(null as string) as item_credit_prc_2,
  cast(null as string) as item_usage_nbr,
  cast(null as string) as main_item_mtl_prc_grp_cd,
  cast(null as string) as main_item_mtl_prc_grp_nm,
  cast(null as string) as main_item_prc_ref_sku,
  cast(null as string) as manual_prc_chng_stat_cd,
  cast(null as double) as mfg_cost_co_curncy_amt,
  cast(null as string) as mfg_cost_key,
  cast(null as string) as mfg_cost_rule_cd,
  cast(null as string) as mfg_usd_curncy_mth_rt_key,
  cast(null as string) as mtl_determ_nbr,
  cast(null as string) as mtl_grp_1_cd,
  cast(null as string) as mtl_grp_1_nm,
  cast(null as string) as mtl_grp_2_cd,
  cast(null as string) as mtl_grp_2_nm,
  cast(null as string) as mtl_grp_3_cd,
  cast(null as string) as mtl_grp_3_nm,
  cast(null as string) as mtl_grp_4_cd,
  cast(null as string) as mtl_grp_4_nm,
  cast(null as string) as mtl_grp_5_cd,
  cast(null as string) as mtl_grp_5_nm,
  cast(null as string) as mtl_grp_cd,
  cast(null as string) as mtl_grp_nm,
  cast(null as string) as mtl_prc_grp_cd,
  cast(null as string) as mtl_prc_grp_nm,
  cast(Dinvoice.DInvoiceSalesAmt as double) as net_val_lcur_amt,
  cast(null as string) as next_ord_stat_cd,
  cast(null as string) as next_ord_stat_nm,
  cast(null as string) as ord_cat_cd,
  cast(null as string) as ord_cat_nm,
  cast(null as string) as ord_line_cat_cd,
  cast(null as string) as ord_line_cat_nm,
  cast(null as string) as ord_mode_cd,
  cast(null as string) as ord_mode_nm,
  cast(null as string) as ord_taken_by_nm,
  cast(null as string) as org_unit_cd,
  cast(null as string) as org_unit_nm,
  cast(null as string) as org_unit_type,
  cast(null as string) as orig_doc_nbr,
  cast(null as string) as orig_item_nbr,
  cast(null as string) as parent_grp_purch_org_cd,
  cast(null as string) as parent_grp_purch_org_nm,
  cast(null as string) as parent_sold_to_cust_id,
  cast(null as string) as parent_sold_to_cust_key,
  cast(null as string) as parent_sold_to_cust_nm,
  cast(null as string) as payer_cust_id,
  cast(null as string) as payer_cust_key,
  cast(null as string) as payer_cust_nm,
  cast(null as string) as paymt_guarnt_form_cd,
  cast(null as string) as paymt_guarnt_form_nm,
  cast(null as string) as paymt_plan_cd,
  cast(null as string) as paymt_plan_nbr,
  cast(null as string) as paymt_plan_nm,
  cast(null as string) as pis_tax_law_cd,
  cast(null as string) as pis_tax_law_nm,
  cast(null as string) as plant_cd,
  cast(null as string) as plant_key,
  cast(null as string) as plant_nm,
  cast(null as string) as prc_exch_rt,
  cast(null as decimal(38,0)) as prc_exch_rt_dt_key,
  cast(null as string) as prc_incomplt_flg,
  cast(IDH.Idh_price as double) as prc_per_unit_amt,
  cast(null as string) as prc_proc_subtot_1,
  cast(null as string) as prc_proc_subtot_2,
  cast(null as string) as prc_proc_subtot_3,
  cast(null as string) as prc_proc_subtot_4,
  cast(null as string) as prc_proc_subtot_5,
  cast(null as string) as prc_proc_subtot_6,
  cast(null as string) as prod_cost_hist_key,
  cast(null as string) as prod_cost_key,
  cast(null as string) as prod_gross_wgt,
  cast(null as string) as prod_hier_str,
  "msd_qad_lower([company.companydomain])"||'|'||CASE WHEN ih_fsm_type = 'SC' THEN idh_for ELSE idh_part END ) as prod_key,
  cast(null as string) as prod_line_cd,
  cast(null as string) as prod_net_wgt,
  cast(null as string) as prod_ord_nbr,
  cast(null as string) as prod_plant_key,
  cast(null as string) as prod_prc_ref_sku,
  cast(null as string) as prod_tax_class_1_cd,
  cast(null as string) as prod_tax_class_2_cd,
  cast(null as string) as prod_tax_class_3_cd,
  cast(null as string) as prod_tax_class_4_cd,
  cast(null as string) as prod_vol,
  cast(null as string) as profit_center_cd,
  cast(null as string) as profit_center_key,
  cast(null as string) as profit_center_nm,
  cast(null as string) as profit_seg_nbr,
  cast(IDH.idh_project as string) as proj_cd,
  cast(null as string) as promo_cd,
  cast(null as string) as promo_id,
  cast(null as string) as prtnr_seg_item_nbr,
  cast(null as string) as rebate_basis_cd,
  current_timestamp as rec_crt_ts,
  current_timestamp as rec_updt_ts,
  cast(null as string) as ref_doc_line_nbr,
  cast(null as string) as ref_doc_nbr,
  cast(null as string) as ref_ord_cat_cd,
  cast(null as string) as ref_ord_cat_nm,
  cast(null as string) as return_item_flg,
  cast(null as string) as revnu_div_cd,
  cast(null as string) as revnu_recogn_cat_cd,
  cast(null as string) as rgn_cd,
  cast(null as string) as rgn_nm,
  cast(null as string) as sd_tax_cd,
  cast(null as string) as ship_nbr,
  cast(null as string) as ship_point_cd,
  cast(null as string) as ship_point_nm,
  cast(null as string) as ship_to_addr_cd,
  cast(null as string) as ship_to_addr_key,
  cast(null as string) as ship_to_bus_area_cd,
  cast(dinvoice.dinvoiceshiptocode as string) as ship_to_cust_id,
  concat("msd_qad_",lower(company.companydomain))||'|'||dinvoice.dinvoiceshiptocode as ship_to_cust_key,
  cast(null as string) as ship_to_cust_nm,
  cast(null as string) as ship_to_cust_sls_key,
  cast(null as string) as ship_to_distrb_chnl_cd,
  cast(null as string) as ship_to_sls_org_cd,
  CASE WHEN ih_fsm_type = 'SC' THEN idh_for ELSE idh_part END as sku,
  cast(null as string) as sku_nm,
  cast(null as string) as sls_cntry_hier_key,
  cast(null as string) as sls_doc_ref_flg,
  cast(null as string) as sls_grp_cd,
  cast(null as string) as sls_grp_nm,
  concat("msd_qad_",company.companydomain)||'|'||DInvoice.dinvoiceditext||'|'||COALESCE (idh_hist.idh_line, 1)||'|'||Dinvoice.dinvoicedate||'|'||Dinvoice.dinvoice_id ||'|'|| CASE WHEN ih_fsm_type = 'SC' THEN concat(ih_sa_nbr ||'|'|| ih_nbr else ih_nbr END ||'|'||Debtor.debtorcode||'|'||TRIM (CASE WHEN ih_fsm_type = 'SC' THEN idh_for ELSE idh_part END) as sls_invc_key,
  COALESCE (idh_hist.idh_line, 1) as sls_invc_line_nbr,
  cast(DI.dinvoiceditext as string) as sls_invc_nbr,
  cast(null as string) as sls_office_cd,
  cast(null as string) as sls_office_nm,
  cast(null as string) as sls_ord_bus_area_cd,
  cast(null as string) as sls_ord_bus_area_nm,
  cast(IH.ih_ord_date as int) as sls_ord_crt_dt_key,
  cast(null as string) as sls_ord_cust_grp_cd,
  cast(null as string) as sls_ord_cust_grp_nm,
  cast(null as string) as sls_ord_distrb_chnl_cd,
  cast(null as string) as sls_ord_distrb_chnl_nm,
  cast(IDH.idh_line as string) as sls_ord_line_nbr,
  CASE WHEN ih_fsm_type = 'SC' THEN ih_sa_nbr ELSE ih_nbr END as sls_ord_nbr,
  cast(null as string) as sls_ord_prc_grp_cd,
  cast(null as string) as sls_ord_prc_grp_nm,
  cast(null as string) as sls_ord_prc_list_type_cd,
  cast(null as string) as sls_ord_prc_list_type_nm,
  cast(null as string) as sls_ord_rsn_cd,
  cast(null as string) as sls_ord_rsn_nm,
  cast(null as string) as sls_ord_sfx_cd,
  cast(null as string) as sls_ord_sls_district_cd,
  cast(null as string) as sls_ord_sls_district_nm,
  cast(null as string) as sls_ord_sls_org_cd,
  cast(null as string) as sls_ord_sls_org_key,
  cast(null as string) as sls_ord_sls_org_nm,
  cast(null as string) as sls_org_key,
  cast(null as double) as sls_qty_conv_dnmntr,
  cast(null as double) as sls_qty_conv_nmrtr,
  cast(null as string) as sls_rep_cust_id,
  cast(null as string) as sls_rep_cust_key,
  cast(null as string) as sls_rep_cust_nm,
  cast(null as string) as sls_terr_cd,
  cast(IDH.idh_um as string) as sls_uom_cd,
  cast(null as string) as sls_uom_nm,
  cast(null as string) as sold_to_bus_area_cd,
  cast(Debtor.debtorcode as string) as sold_to_cust_id,
  concat("msd_qad_",lower(company.companydomain))||'|'||Debtor.debtorcode as sold_to_cust_key,
  cast(null as string) as sold_to_cust_nm,
  cast(null as string) as sold_to_cust_sls_key,
  cast(null as string) as sold_to_distrb_chnl_cd,
  cast(null as string) as sold_to_sls_org_cd,
  cast(null as string) as src_crt_by,
  cast(DI.dinvoicedate as timestamp) as src_crt_ts,
  concat("msd_qad_",lower(company.companydomain)) as src_sys_cd,
  cast(DI.LastModifiedUser as string) as src_updt_by,
  cast(DI.LastModifiedTime as timestamp) as src_updt_ts,
  cast(null as string) as st_prov_cd,
  cast(null as string) as st_prov_nm,
  cast(null as string) as statis_exch_rt,
  cast(null as string) as statis_updt_grp_cd,
  cast(null as string) as statis_val_flg,
  cast(null as double) as stk_keep_invc_qty,
  cast(null as double) as stk_keep_req_qty,
  cast(null as string) as stop_cd,
  cast(null as string) as stop_nm,
  cast(null as string) as strg_loc_cd,
  cast(null as string) as strg_loc_nm,
  cast(null as decimal(38,0)) as svc_render_dt_key,
  cast(null as string) as tax_juris_id,
  cast(null as double) as tax_lcur_amt,
  cast(null as decimal(38,0)) as transl_dt_key,
  cast(null as string) as web_user_cust_id,
  cast(null as string) as web_user_cust_key,
  cast(null as string) as web_user_cust_nm,
  cast(null as string) as wgt_uom_cd,
  cast(null as string) as wgt_uom_nm
from DInvoice DI
  inner join company C on C.company_id=DI.company_id
  inner join debtor DEB on DEB.debtor_id=DI.debtor_id
  inner join businessrelation BR on BR.businessrelation_id=DEB.businessrelation_id
  inner join ad_mstr AD on AD.ad_addr=DEB.debtorcode AND AD.ad_domain=C.companydomain
  inner join ih_hist IH on IH.ih_domain=C.companydomain and ih.ih_inv_nbr=DI.dinvoiceditext
  inner join idh_hist IDH on IDH.idh_domain=IH.ih_domain and IDH.idh_inv_nbr=IH.ih_inv_nbr and IDH.idh_nbr=IH.ih_nbr
  inner join pt_mstr PT on PT.pt_domain=IDH.idh_domain and PT.pt_part=CASE when IH.ih_fsm_type='SC' THEN IDH.idh_for ELSE idh.idh_part END
  left join ad_mstr AD2 on AD2.ad_addr=DI.dinvoiceshiptocode and lower(AD2.ad_domain)=lower(company.companydomain)
  left join gl GL on GL.gl_id=DI.controlgl_id
  left join d_drm_hier_map_hist DHM on DHM.bus_map_val=dinvoice.company_id and DHM.drm_hier_gl_str like (case when gl.glcode like (‘1%’) or (‘2%’) or (‘3%’) then (‘%C2NONE%’) else (‘%UNKNOWNBL%’) and DHM.src_sys_cd like (‘%company.companydomain%’)
where src_sys_cd like (‘%qad%’) and current_rec_flg=’Y’ (idh_hist.idh_nbr= ih_hist.ih_sa_nbr OR (idh_hist.idh_nbr=ih_hist.ih_nbr)
)))