-- Query: KAN-13_transformation
-- Purpose: Generated SQL for KAN-13 via 7-stage pipeline
-- Query Type: SELECT

WITH constants_cluster_defaults AS (
    SELECT
        CAST(NULL AS STRING) AS cust_id,
        CAST(NULL AS STRING) AS cust_nm,
        CAST(NULL AS STRING) AS cust_nm_en,
        CAST(NULL AS STRING) AS cust_type_cd,
        CAST(NULL AS STRING) AS cust_type_nm,
        CAST(NULL AS STRING) AS active_flg,
        CAST(NULL AS STRING) AS parent_cust_id,
        CAST(NULL AS STRING) AS parent_cust_nm,
        CAST(NULL AS STRING) AS naics_cd,
        CAST(NULL AS STRING) AS naics_nm,
        CAST(NULL AS STRING) AS sic_cd,
        CAST(NULL AS STRING) AS sic_nm,
        CAST(NULL AS STRING) AS gbl_govt_id,
        CAST(NULL AS STRING) AS gbl_loc_nbr,
        CAST(NULL AS STRING) AS dnb_duns_nm,
        CAST(NULL AS STRING) AS alt_payer_cust_id,
        CAST(NULL AS STRING) AS annl_sls_amt,
        CAST(NULL AS STRING) AS central_bill_block_cd,
        CAST(NULL AS STRING) AS central_bill_block_nm,
        CAST(NULL AS STRING) AS central_delvr_block_cd,
        CAST(NULL AS STRING) AS central_delvr_block_nm,
        CAST(NULL AS STRING) AS central_ord_block_cd,
        CAST(NULL AS STRING) AS central_ord_block_nm,
        CAST(NULL AS STRING) AS cust_acct_grp_cd,
        CAST(NULL AS STRING) AS cust_acct_grp_nm,
        CAST(NULL AS STRING) AS cust_class_cd,
        CAST(NULL AS STRING) AS cust_class_nm,
        CAST(NULL AS STRING) AS curncy_cd,
        CAST(NULL AS STRING) AS curncy_nm,
        CAST(NULL AS STRING) AS indy_cd,
        CAST(NULL AS STRING) AS indy_nm,
        CAST(NULL AS STRING) AS intl_loc_nbr_check_digit,
        CAST(NULL AS STRING) AS lang_cd,
        CAST(NULL AS STRING) AS lang_iso_cd,
        CAST(NULL AS STRING) AS lang_nm,
        CAST(NULL AS STRING) AS lgl_stat_cd,
        CAST(NULL AS STRING) AS lgl_stat_nm,
        CAST(NULL AS STRING) AS rgn_mkt,
        CAST(NULL AS STRING) AS sls_since_yr,
        CAST(NULL AS STRING) AS sort_field,
        CAST(NULL AS STRING) AS tax_juris_cd,
        CAST(NULL AS STRING) AS tax_juris_nm,
        CAST(NULL AS STRING) AS teletex_nbr,
        CAST(NULL AS STRING) AS telex_nbr,
        CAST(NULL AS STRING) AS title,
        CAST(NULL AS STRING) AS transp_zone_cd,
        CAST(NULL AS STRING) AS transp_zone_nm,
        CAST(NULL AS STRING) AS trading_prtnr_co_cd,
        CAST(NULL AS STRING) AS url,
        CAST(NULL AS STRING) AS unload_point_flg,
        CAST(NULL AS STRING) AS vat_regstr_nbr,
        CAST(NULL AS STRING) AS central_del_block_flg,
        CAST(NULL AS STRING) AS central_del_flg,
        CAST(NULL AS STRING) AS central_post_block_flg,
        CAST(NULL AS STRING) AS central_sls_block_flg,
        CAST(NULL AS STRING) AS cmptr_flg,
        CAST(NULL AS STRING) AS natural_pers_flg,
        CAST(NULL AS STRING) AS one_time_cust_flg,
        CAST(NULL AS STRING) AS sls_prtnr_flg,
        CAST(NULL AS STRING) AS sls_prospect_flg,
        CAST(NULL AS STRING) AS addr_key,
        CAST(NULL AS STRING) AS street_line,
        CAST(NULL AS STRING) AS pstl_cd,
        CAST(NULL AS STRING) AS city,
        CAST(NULL AS STRING) AS city_coord,
        CAST(NULL AS STRING) AS po_box,
        CAST(NULL AS STRING) AS po_box_pstl_cd,
        CAST(NULL AS STRING) AS district,
        CAST(NULL AS STRING) AS st_prov_cd,
        CAST(NULL AS STRING) AS st_prov_nm,
        CAST(NULL AS STRING) AS cntry_cd,
        CAST(NULL AS STRING) AS cntry_nm,
        CAST(NULL AS STRING) AS fax_nbr,
        CAST(NULL AS STRING) AS trading_prtnr_co_nm,
        CAST(NULL AS STRING) AS prim_contact_key,
        CAST(NULL AS STRING) AS dnb_duns_nbr,
        CAST(NULL AS STRING) AS addr_nm_line2,
        CAST(NULL AS STRING) AS addr_nm_line3,
        CAST(NULL AS STRING) AS addr_nm_line4,
        CAST(NULL AS STRING) AS cust_cond_grp_cd1,
        CAST(NULL AS STRING) AS cust_cond_grp_cd2,
        CAST(NULL AS STRING) AS cust_cond_grp_nm1,
        CAST(NULL AS STRING) AS cust_cond_grp_nm2,
        CAST(NULL AS STRING) AS cust_email_addr_txt,
        CAST(NULL AS STRING) AS cust_rept_hier_base,
        CAST(NULL AS STRING) AS dw_src_key,
        CAST(NULL AS STRING) AS indy_cd1,
        CAST(NULL AS STRING) AS indy_cd2,
        CAST(NULL AS STRING) AS indy_nm1,
        CAST(NULL AS STRING) AS indy_nm2,
        CAST(NULL AS STRING) AS intl_loc_nbr1,
        CAST(NULL AS STRING) AS intl_loc_nbr2,
        CAST(NULL AS STRING) AS phn_nbr1,
        CAST(NULL AS STRING) AS phn_nbr2,
        CAST(NULL AS STRING) AS search_mcode1,
        CAST(NULL AS STRING) AS search_mcode2,
        CAST(NULL AS STRING) AS search_mcode3,
        CAST(NULL AS STRING) AS sply_center_cd,
        CAST(NULL AS STRING) AS sply_center_flg,
        CAST(NULL AS STRING) AS sply_center_nm,
        CAST(NULL AS STRING) AS tax_nbr1,
        CAST(NULL AS STRING) AS tax_nbr2,
        CAST(NULL AS STRING) AS tax_nbr3,
        CAST(NULL AS STRING) AS src_crt_by,
        CAST(NULL AS STRING) AS src_crt_ts,
        CAST(NULL AS STRING) AS src_updt_by,
        CAST(NULL AS STRING) AS src_updt_ts,
        CAST(NULL AS STRING) AS rec_crt_ts,
        CAST(NULL AS STRING) AS rec_updt_ts,
        CAST(NULL AS STRING) AS stock_ticker_cd,
        CAST(NULL AS STRING) AS cdw_cust_key,
        CAST(NULL AS STRING) AS dw_cust_key,
        CAST(NULL AS STRING) AS addr_phn_nbr,
        CAST(NULL AS STRING) AS addr_fax_nbr,
        CAST(NULL AS STRING) AS sls_chnl_cd,
        CAST(NULL AS STRING) AS sls_terr_cd,
        CAST(NULL AS STRING) AS sls_rep_cust_key,
        CAST(NULL AS STRING) AS addr_type_cd,
        CAST(NULL AS STRING) AS hfm_entity_key,
        CAST(NULL AS STRING) AS hfm_entity_cd,
        CAST(NULL AS STRING) AS deflt_delvr_cntry_key,
        CAST(NULL AS STRING) AS deflt_delvr_cntry_cd,
        CAST(NULL AS STRING) AS trade_chnl_cd,
        CAST(NULL AS STRING) AS county,
        CAST(NULL AS STRING) AS temporary_flag,
        CAST(NULL AS STRING) AS bank_acct_1,
        CAST(NULL AS STRING) AS coc_number,
        CAST(NULL AS STRING) AS tax_id_federal,
        CAST(NULL AS STRING) AS tax_type,
        CAST(NULL AS STRING) AS tax_class_code,
        CAST(NULL AS STRING) AS taxable_flag,
        CAST(NULL AS STRING) AS tax_in_flag,
        CAST(NULL AS STRING) AS netting_logic,
        CAST(NULL AS STRING) AS trading_prtnr_interface_id,
        CAST(NULL AS STRING) AS edi_control,
        CAST(NULL AS STRING) AS time_zone,
        CAST(NULL AS STRING) AS trading_prtnr_edi_id,
        CAST(NULL AS STRING) AS barcode_label_print_program,
        CAST(NULL AS STRING) AS barcode_validation_program,
        CAST(NULL AS STRING) AS calendar,
        CAST(NULL AS STRING) AS edi_standard,
        CAST(NULL AS STRING) AS edi_standard_level,
        CAST(NULL AS STRING) AS trd_partner_location_code,
        CAST(NULL AS STRING) AS tax_zone,
        CAST(NULL AS STRING) AS tax_id_misc_1,
        CAST(NULL AS STRING) AS tax_id_misc_2,
        CAST(NULL AS STRING) AS tax_id_misc_3,
        CAST(NULL AS STRING) AS week_offset,
        CAST(NULL AS STRING) AS invoices_via,
        CAST(NULL AS STRING) AS schedules_via,
        CAST(NULL AS STRING) AS purchase_orders_via,
        CAST(NULL AS STRING) AS asn_default_data,
        CAST(NULL AS STRING) AS intrastat_division,
        CAST(NULL AS STRING) AS tax_report_flag,
        CAST(NULL AS STRING) AS name_control,
        CAST(NULL AS STRING) AS last_filing_flag,
        CAST(NULL AS STRING) AS priority,
        CAST(NULL AS STRING) AS route,
        CAST(NULL AS STRING) AS load_sequence,
        CAST(NULL AS STRING) AS pick_by_date,
        CAST(NULL AS STRING) AS profile,
        CAST(NULL AS STRING) AS tac_in_city_flag,
        CAST(NULL AS STRING) AS non_sales_price_list,
        CAST(NULL AS STRING) AS business_relation,
        CAST(NULL AS STRING) AS alternate_um,
        CAST(NULL AS STRING) AS city_code
),
ad_mstr_related_logic_source AS (
    SELECT
        ad_mstr.ad_domain,
        ad_mstr.ad_addr
    FROM ad_mstr
    LEFT JOIN cm_mstr ON upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr) AND upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
    LEFT JOIN currency curr ON curr.currencycode = cm_mstr.cm_curr
    JOIN d_cntry_hier dch ON upper(ad_mstr.ad_ctry) = upper(dch.cntry_alpha2_cd)
    WHERE ad_mstr.ad_domain IS NOT NULL AND ad_mstr.ad_addr IS NOT NULL
),
ad_mstr_related_logic_transformed AS (
    SELECT
        concat('msd_qad_', lower(ad_mstr.ad_domain), '|', ad_mstr.ad_addr) AS cust_key,
        concat('msd_qad_', lower(ad_mstr.ad_domain)) AS src_sys_cd,
        CASE 
            WHEN ad_mstr.ad_addr LIKE 'Z%' OR ad_mstr.ad_addr LIKE 'TM%' THEN 'IC'
            ELSE '3rd'
        END AS inter_co_cd
    FROM ad_mstr_related_logic_source
)
SELECT * FROM ad_mstr_related_logic_transformed;