/**********************************************************************
artefact name :- d_customer
description   :- d_customer sql generated from mapping
----------------------------------------------------------------------
change log
version :   date :        description :                       changed by
----------------------------------------------------------------------
0.0         2026-07-16    auto-generated from mapping         ai_agent
**********************************************************************/

select 
        concat('msd_qad_', lower(ad.ad_domain)) || ad.ad_addr as cust_key,
    concat('msd_qad_', lower(ad.ad_domain)) || ad.ad_addr as src_sys_cd,
    cast(cm.cm_addr as string) as cust_id,
    cast(ad.ad_name as string) as cust_nm,
    cast(ad.ad_name as string) as cust_nm_en,
    cast(ad.ad_type as string) as cust_type_cd,
    cast(ad.ad_type as string) as cust_type_nm,
    cast(null as string) as active_flg,
    cast(null as string) as parent_cust_id,
    cast(null as string) as parent_cust_nm,
    cast(null as string) as naics_cd,
    cast(null as string) as naics_nm,
    cast(null as string) as sic_cd,
    cast(null as string) as sic_nm,
    cast(null as string) as gbl_govt_id,
    cast(null as string) as gbl_loc_nbr,
    cast(null as string) as dnb_duns_nm,
    cast(null as string) as alt_payer_cust_id,
    cast(null as string) as annl_sls_amt,
    cast(null as string) as central_bill_block_cd,
    cast(null as string) as central_bill_block_nm,
    cast(null as string) as central_delvr_block_cd,
    cast(null as string) as central_delvr_block_nm,
    cast(null as string) as central_ord_block_cd,
    cast(null as string) as central_ord_block_nm,
    cast(null as string) as cust_acct_grp_cd,
    cast(null as string) as cust_acct_grp_nm,
    cast(null as string) as cust_class_cd,
    cast(null as string) as cust_class_nm,
    cast(cm_mstr.cm_curr as string) as curncy_cd,
    cast(currency.currencydescription as string) as curncy_nm,
    cast(null as string) as indy_cd,
    cast(null as string) as indy_nm,
    cast(null as string) as intl_loc_nbr_check_digit,
    cast(ad.ad_lang as string) as lang_cd,
    cast(null as string) as lang_iso_cd,
    cast(null as string) as lang_nm,
    cast(null as string) as lgl_stat_cd,
    cast(null as string) as lgl_stat_nm,
    cast(null as string) as rgn_mkt,
    cast(null as string) as sls_since_yr,
    cast(ad.ad_sort as string) as sort_field,
    cast(ad.ad_tax_usage as string) as tax_juris_cd,
    cast(null as string) as tax_juris_nm,
    cast(null as string) as teletex_nbr,
    cast(null as string) as telex_nbr,
    cast(null as string) as title,
    cast(null as string) as transp_zone_cd,
    cast(null as string) as transp_zone_nm,
    cast(null as string) as trading_prtnr_co_cd,
    cast(null as string) as url,
    cast(null as string) as unload_point_flg,
    cast(ad.ad_vat_reg as string) as vat_regstr_nbr,
    cast(null as string) as central_del_block_flg,
    cast(null as string) as central_del_flg,
    cast(null as string) as central_post_block_flg,
    cast(null as string) as central_sls_block_flg,
    cast(null as string) as cmptr_flg,
    cast(null as string) as natural_pers_flg,
    cast(null as string) as one_time_cust_flg,
    cast(null as string) as sls_prtnr_flg,
    cast(null as string) as sls_prospect_flg,
    cast(ad_mstr.ad_address_id as string) as addr_key,
    cast(ad_mstr.ad_line2 as string) as street_line,
    cast(ad_mstr.ad_zip as string) as pstl_cd,
    cast(ad_mstr.ad_city as string) as city,
    cast(null as string) as city_coord,
    cast(null as string) as po_box,
    cast(null as string) as po_box_pstl_cd,
    cast(null as string) as district,
    cast(ad_mstr.ad_state as string) as st_prov_cd,
    cast(null as string) as st_prov_nm,
    cast(ad_mstr.ad_ctry as string) as cntry_cd,
    cast(ad_mstr.ad_country as string) as cntry_nm,
    cast(ad_mstr.ad_fax as string) as fax_nbr,
    cast(null as string) as calendar,
    cast(null as string) as ad__qad01,
    cast(null as string) as ad__qad02,
    cast(null as string) as ad__qad03,
    cast(null as string) as ad__qad04,
    cast(null as string) as ad__qad05,
    cast(null as string) as ad__chr01,
    cast(null as string) as ad__chr02,
    cast(null as string) as ad__chr03,
    cast(null as string) as ad__chr04,
    cast(null as string) as ad__chr05,
    cast(null as string) as ad_email2,
    cast(null as string) as priority,
    cast(null as string) as route,
    cast(null as string) as profile
from ad_mstr ad
inner join cm_mstr cm
    on ad.ad_addr = cm.cm_addr
where lower(ad_domain) = lower(cm_domain)
;