-- Query: KAN-14_transformation
-- Purpose: Generated SQL for KAN-14 via 7-stage pipeline
-- Query Type: SELECT

WITH
main_transformation_cte AS (
    SELECT
        concat('msd_qad_',lower(ad_mstr.ad_domain),'|',ad_mstr.ad_addr) AS cust_key,
        concat('msd_qad_',lower(ad_mstr.ad_domain)) AS src_sys_cd,
        upper(cm_mstr.cm_addr) AS cust_id,
        ad_mstr.ad_name AS cust_nm,
        ad_mstr.ad_name AS cust_nm_en,
        ad_mstr.ad_type AS cust_type_cd,
        ad_mstr.ad_type AS cust_type_nm,
        cast(NULL AS STRING) AS active_flg,
        cast(NULL AS STRING) AS parent_cust_id,
        cast(NULL AS STRING) AS parent_cust_nm,
        cast(NULL AS STRING) AS naics_cd,
        cast(NULL AS STRING) AS naics_nm,
        cast(NULL AS STRING) AS sic_cd,
        cast(NULL AS STRING) AS sic_nm,
        cast(NULL AS STRING) AS gbl_govt_id,
        cast(NULL AS STRING) AS gbl_loc_nbr,
        cast(NULL AS STRING) AS dnb_duns_nm,
        cast(NULL AS STRING) AS alt_payer_cust_id,
        cast(NULL AS DOUBLE) AS annl_sls_amt,
        cast(NULL AS STRING) AS central_bill_block_cd,
        cast(NULL AS STRING) AS central_bill_block_nm,
        cast(NULL AS STRING) AS central_delvr_block_cd,
        cast(NULL AS STRING) AS central_delvr_block_nm,
        cast(NULL AS STRING) AS central_ord_block_cd,
        cast(NULL AS STRING) AS central_ord_block_nm,
        cast(NULL AS STRING) AS cust_acct_grp_cd,
        cast(NULL AS STRING) AS cust_acct_grp_nm,
        cast(NULL AS STRING) AS cust_class_cd,
        cast(NULL AS STRING) AS cust_class_nm,
        cast(cm_mstr.cm_curr AS STRING) AS curncy_cd,
        currency.currencydescription AS curncy_nm,
        cast(NULL AS STRING) AS indy_cd,
        cast(NULL AS STRING) AS indy_nm,
        cast(NULL AS STRING) AS intl_loc_nbr_check_digit,
        ad_mstr.ad_lang AS lang_cd,
        cast(NULL AS STRING) AS lang_iso_cd,
        cast(NULL AS STRING) AS lang_nm,
        cast(NULL AS STRING) AS lgl_stat_cd,
        cast(NULL AS STRING) AS lgl_stat_nm,
        cast(NULL AS STRING) AS rgn_mkt,
        cast(NULL AS STRING) AS sls_since_yr,
        ad_mstr.ad_sort AS sort_field,
        ad_mstr.ad_tax_usage AS tax_juris_cd,
        cast(NULL AS STRING) AS tax_juris_nm,
        cast(NULL AS STRING) AS teletex_nbr,
        cast(NULL AS STRING) AS telex_nbr,
        cast(NULL AS STRING) AS title,
        cast(NULL AS STRING) AS transp_zone_cd,
        cast(NULL AS STRING) AS transp_zone_nm,
        cast(NULL AS STRING) AS trading_prtnr_co_cd,
        cast(NULL AS STRING) AS url,
        cast(NULL AS STRING) AS unload_point_flg,
        ad_mstr.ad_vat_reg AS vat_regstr_nbr,
        cast(NULL AS STRING) AS central_del_block_flg,
        cast(NULL AS STRING) AS central_del_flg,
        cast(NULL AS STRING) AS central_post_block_flg,
        cast(NULL AS STRING) AS central_sls_block_flg,
        cast(NULL AS STRING) AS cmptr_flg,
        cast(NULL AS STRING) AS natural_pers_flg,
        cast(NULL AS STRING) AS one_time_cust_flg,
        cast(NULL AS STRING) AS sls_prtnr_flg,
        cast(NULL AS STRING) AS sls_prospect_flg,
        concat('msd_qad_',lower(ad_mstr.ad_domain),'|',ad_mstr.ad_address_id) AS addr_key,
        ad_mstr.ad_line2 AS street_line,
        ad_mstr.ad_zip AS pstl_cd,
        ad_mstr.ad_city AS city,
        cast(NULL AS STRING) AS city_coord,
        cast(NULL AS STRING) AS po_box,
        cast(NULL AS STRING) AS po_box_pstl_cd,
        cast(NULL AS STRING) AS district,
        ad_mstr.ad_state AS st_prov_cd,
        cast(NULL AS STRING) AS st_prov_nm,
        ad_mstr.ad_ctry AS cntry_cd,
        ad_mstr.ad_country AS cntry_nm,
        ad_mstr.ad_fax AS fax_nbr,
        cast(NULL AS STRING) AS trading_prtnr_co_nm,
        cast(NULL AS STRING) AS prim_contact_key,
        cast(NULL AS STRING) AS dnb_duns_nbr,
        ad_mstr.ad_line1 AS addr_nm_line2,
        ad_mstr.ad_line2 AS addr_nm_line3,
        ad_mstr.ad_line3 AS addr_nm_line4,
        cast(NULL AS STRING) AS cust_cond_grp_cd1,
        cast(NULL AS STRING) AS cust_cond_grp_cd2,
        cast(NULL AS STRING) AS cust_cond_grp_nm1,
        cast(NULL AS STRING) AS cust_cond_grp_nm2,
        ad_mstr.ad_email AS cust_email_addr_txt,
        cast(NULL AS STRING) AS cust_rept_hier_base,
        cast(NULL AS STRING) AS dw_src_key,
        cast(NULL AS STRING) AS indy_cd1,
        cast(NULL AS STRING) AS indy_cd2,
        cast(NULL AS STRING) AS indy_nm1,
        cast(NULL AS STRING) AS indy_nm2,
        cast(NULL AS STRING) AS intl_loc_nbr1,
        cast(NULL AS STRING) AS intl_loc_nbr2,
        ad_mstr.ad_phone AS phn_nbr1,
        ad_mstr.ad_phone2 AS phn_nbr2,
        cast(NULL AS STRING) AS search_mcode1,
        cast(NULL AS STRING) AS search_mcode2,
        cast(NULL AS STRING) AS search_mcode3,
        cast(NULL AS STRING) AS sply_center_cd,
        cast(NULL AS STRING) AS sply_center_flg,
        cast(NULL AS STRING) AS sply_center_nm,
        ad_mstr.ad_pst_id AS tax_nbr1,
        cast(NULL AS STRING) AS tax_nbr2,
        cast(NULL AS STRING) AS tax_nbr3,
        cast(NULL AS STRING) AS src_crt_by,
        cast(ad_mstr.ad_date AS STRING) AS src_crt_ts,
        substr(cm_mstr.cm_mod_date,1,11) AS src_updt_ts,
        current_timestamp AS rec_crt_ts,
        current_timestamp AS rec_updt_ts,
        cast(NULL AS STRING) AS stock_ticker_cd,
        cast(NULL AS STRING) AS cdw_cust_key,
        cast(NULL AS STRING) AS dw_cust_key,
        cast(NULL AS STRING) AS addr_phn_nbr,
        ad_mstr.ad_fax2 AS addr_fax_nbr,
        cast(NULL AS STRING) AS sls_chnl_cd,
        cast(NULL AS STRING) AS sls_terr_cd,
        cast(NULL AS STRING) AS sls_rep_cust_key,
        cast(NULL AS STRING) AS addr_type_cd,
        cast(NULL AS STRING) AS hfm_entity_key,
        cast(NULL AS STRING) AS hfm_entity_cd,
        concat('msd_qad_',lower(ad_mstr.ad_domain),'|',dch.cntry_hier_key) AS deflt_delvr_cntry_key,
        ad_mstr.ad_ctry AS deflt_delvr_cntry_cd,
        cast(NULL AS STRING) AS trade_chnl_cd,
        case when ad_mstr.ad_addr like 'Z%' OR ad_mstr.ad_addr like 'TM%' then 'IC' else '3rd' end AS inter_co_cd,
        cast(NULL AS STRING) AS county,
        cast(NULL AS STRING) AS temporary_flag,
        cast(NULL AS STRING) AS bank_acct_1,
        cast(NULL AS STRING) AS coc_number,
        cast(NULL AS STRING) AS tax_id_federal,
        cast(NULL AS STRING) AS tax_type,
        cast(NULL AS STRING) AS tax_class_code,
        cast(NULL AS STRING) AS taxable_flag,
        cast(NULL AS STRING) AS tax_in_flag,
        cast(NULL AS STRING) AS netting_logic,
        cast(NULL AS STRING) AS trading_prtnr_interface_id,
        cast(NULL AS STRING) AS edi_control,
        cast(NULL AS STRING) AS time_zone,
        cast(NULL AS STRING) AS trading_prtnr_edi_id,
        cast(NULL AS STRING) AS barcode_label_print_program,
        cast(NULL AS STRING) AS barcode_validation_program,
        cast(NULL AS STRING) AS calendar,
        cast(NULL AS STRING) AS edi_standard,
        cast(NULL AS STRING) AS edi_standard_level,
        cast(NULL AS STRING) AS trd_partner_location_code,
        cast(NULL AS STRING) AS tax_zone,
        cast(NULL AS STRING) AS tax_id_misc_1,
        cast(NULL AS STRING) AS tax_id_misc_2,
        cast(NULL AS STRING) AS tax_id_misc_3,
        cast(NULL AS STRING) AS week_offset,
        cast(NULL AS STRING) AS invoices_via,
        cast(NULL AS STRING) AS schedules_via,
        cast(NULL AS STRING) AS purchase_orders_via,
        cast(NULL AS STRING) AS asn_default_data,
        cast(NULL AS STRING) AS intrastat_division,
        cast(NULL AS STRING) AS tax_report_flag,
        cast(NULL AS STRING) AS name_control,
        cast(NULL AS STRING) AS last_filing_flag,
        cast(NULL AS STRING) AS priority,
        cast(NULL AS STRING) AS route,
        cast(NULL AS STRING) AS load_sequence,
        cast(NULL AS STRING) AS pick_by_date,
        cast(NULL AS STRING) AS profile,
        cast(NULL AS STRING) AS tac_in_city_flag,
        cast(NULL AS STRING) AS non_sales_price_list,
        cast(NULL AS STRING) AS business_relation,
        cast(NULL AS STRING) AS alternate_um,
        cast(NULL AS STRING) AS city_code
    FROM ad_mstr
    LEFT JOIN cm_mstr ON upper(cm_mstr.cm_addr) = upper(ad_mstr.ad_addr) AND upper(cm_mstr.cm_domain) = upper(ad_mstr.ad_domain)
    LEFT JOIN currency curr ON curr.currencycode = cm_mstr.cm_curr
    JOIN d_cntry_hier dch ON upper(ad_mstr.ad_ctry) = upper(dch.cntry_alpha2_cd)
    WHERE ad_mstr.ad_domain IS NOT NULL AND ad_mstr.ad_addr IS NOT NULL
)
SELECT * FROM main_transformation_cte;