-- Source: KAN-27
-- Target: f_dly_open_order
-- Branches: 3
-- Fields: 115
-- Unresolved: 245
-- Pipeline Run: pipeline-KAN-27
-- Validation: WARNINGS

WITH
fact_daily_open_order_uisc AS (
  select
  concat("msd_qad_",lower(sa_mstr.sa_domain))||'|'||ETL Load Date YYYYMMDD||'|'||sa_mstr.sa_nbr||'|'||sad_det.sad_ui_line||'|'||sad.det.sad_serial as dly_open_ord_key,
  concat("msd_qad_",lower(sa_mstr.sa_domain))||'|'||ETL Load Date YYYYMMDD||'|'||sa_mstr.sa_nbr||'|'||sad_det.sad_ui_line||'|'||sad.det.sad_serial as src_sys_cd,
  cast(null as decimal(38,0)) as as_of_dt_key,
  cast(sa.sa_nbr as string) as sls_ord_nbr,
  cast(sad.sad_ui_line as string) as sls_ord_line_nbr,
  cast(null as string) as dw_src_cd,
  cast(null as string) as dw_dly_open_ord_key,
  cast(null as string) as src_crt_by,
  cast(sa.sa_ord_date as timestamp) as src_crt_ts,
  cast(sad.sad_mod_userid as string) as src_updt_by,
  cast(sad.sad_mod_date as timestamp) as src_updt_ts,
  current_timestamp as rec_crt_ts,
  current_timestamp as rec_updt_ts,
  concat('msd_qad_',lower(sa_mstr.ad_domain))||'|'||sa_mstr.sa_cust as bill_to_cust_key,
  cast(debtor.debtorcode as string) as bill_to_cust_id,
  cast(null as string) as bill_to_cust_nm,
  cast(null as double) as bo_co_curncy_amt,
  cast(null as string) as bo_flg,
  cast(null as double) as bo_lcur_amt,
  cast(null as double) as bo_qty,
  cast(null as string) as ccg_lcd_chnl,
  cast(null as string) as ccg_lcd_vndr_nbr,
  cast(null as string) as contact_key,
  cast(null as string) as co_usd_curncy_mth_rt_key,
  concat('msd_qad_',lower(si_mstr.si_domain))||'|'||si_mstr.si_entity as co_key,
  cast(si.si_entity as string) as co_cd,
  cast(si.si_desc as string) as co_nm,
  cast(null as string) as co_curncy_cd,
  cast(sad.sad_serial as string) as cur_lot_nbr,
  cast(null as string) as cust_po_nbr,
  cast(null as string) as derived_prod_key,
  cast(null as string) as derived_sku,
  cast(null as string) as derived_sku_nm,
  cast(null as decimal(38,0)) as expect_ship_dt_key,
  cast(null as double) as fin_bo_co_curncy_amt,
  cast(null as double) as fin_bo_lcur_amt,
  cast(null as double) as fin_bo_qty,
  cast(null as string) as fin_ord_line_complt_flg,
  cast(null as string) as hfm_entity_key,
  cast(null as string) as hfm_entity_cd,
  cast(idh.idh_qty_inv as double) as invc_qty,
  cast(null as decimal(38,0)) as mtl_avbl_dt_key,
  cast(null as double) as ord_co_curncy_amt,
  cast(sa.sa_curr as string) as ord_curncy_cd,
  cast(concat('msd_qad_',lower(ca_mstr.ca_domain))||'|'||sa.sa_ord_date as decimal(38,0)) as ord_dt_key,
  cast(null as string) as ord_hdr_usd_curncy_mth_rt_key,
  cast(null as double) as ord_lcur_amt,
  cast(null as string) as strg_loc_cd,
  cast(null as string) as req_strg_loc_cd,
  cast(null as decimal(38,0)) as ord_line_ship_nlt_dt_key,
  cast(sad.sad_qty_per as double) as ord_qty,
  cast(null as decimal(38,0)) as orig_proms_dt_key,
  cast(null as string) as plant_key,
  cast(null as string) as plant_cd,
  cast(null as string) as plant_nm,
  concat('msd_qad_',lower(sad_det.sad_domain))||'|'||sad_det.sad_for as prod_key,
  cast(sad.sad_for as string) as sku,
  cast(null as string) as sku_nm,
  cast(null as string) as prod_plant_key,
  cast(null as decimal(38,0)) as proms_delvr_dt_key,
  cast(null as decimal(38,0)) as req_delvr_dt_key,
  case 
when isb_warr_cd='WPEND' or upper(isb_warr_cd) like ('I%') then 'Install'
when upper(isb_warr_cd) like ('W%') and isb_warr_exp >= current_date then 'Warranty'
when sad_st_date <= current_date and sad_end_date > current_date then 'Contract'
else 'T&M' end as revnu_div,
  cast(null as decimal(38,0)) as ord_rls_dt_key,
  cast(null as double) as ship_qty,
  concat('msd_qad_',lower(sad_det.sad_domain))||'|'||sad_det.sad_eu_nbr as ship_to_cust_key,
  cast(sad.sad_eu_nbr as string) as ship_to_cust_id,
  cast(null as string) as ship_to_cust_nm,
  cast(null as string) as ship_to_cntry_hier_key,
  cast(null as string) as sls_ord_key,
  concat('msd_qad_',lower(sa_mstr.sa_domain))||'|'||sa_mstr.sa_cust as sold_to_cust_key,
  cast(debtor.debtorcode as string) as sold_to_cust_id,
  cast(null as string) as sold_to_cust_nm,
  cast(null as double) as target_qty,
  cast(null as double) as unit_std_cost,
  cast(null as string) as cur_ord_stat_cd,
  cast(null as string) as cur_ord_stat_nm,
  cast(null as string) as next_ord_stat_cd,
  cast(null as string) as next_ord_stat_nm,
  cast(null as string) as hdr_bill_block_cd,
  cast(null as string) as hdr_bill_block_nm,
  cast(null as string) as hdr_delvr_block_cd,
  cast(null as string) as hdr_delvr_block_nm,
  cast(null as string) as bill_block_cd,
  cast(null as string) as bill_block_nm,
  cast(null as string) as delvr_block_cd,
  cast(null as string) as delvr_block_nm,
  cast(null as string) as overall_stat_cd,
  cast(null as string) as overall_stat_nm,
  cast(null as string) as reject_rsn_cd,
  cast(null as string) as reject_rsn_nm,
  cast(null as string) as ord_type_cd,
  cast(null as string) as ord_type_nm,
  cast(null as string) as ord_overall_stat_cd,
  cast(null as string) as ord_overall_stat_nm,
  cast(null as string) as hdr_ord_type_cd,
  cast(null as string) as hdr_ord_type_nm,
  cast(null as string) as bo_stat_nm,
  cast(null as decimal(38,0)) as commit_dt_key,
  cast(null as decimal(38,0)) as proms_ship_dt_key,
  cast(null as decimal(38,0)) as sched_ship_dt_key,
  cast(null as string) as cust_key,
  cast(null as string) as sls_rep_cust_key,
  cast(sad.sad_po as string) as po_nbr,
  cast(null as string) as po_line_nbr,
  case
when lower(costcentre.customcombo0)='UnknownMD' then 'UNKNOWNMD' 
else  replace(replace(upper(costcentre.customlong0),'.',''),'_','') end as business_unit as bu_cd,
  cast(null as string) as sls_terr_cd,
  cast(null as string) as cost_curncy_cd,
  cast(idh.idh_um as string) as uom_cd,
  cast(sad.sad_price as double) as prc_per_unit_amt,
  cast(sad.sad_price as double) as ord_prc_per_unit_amt,
  cast(null as double) as disc_amt,
  cast((sad_price * sad_qty_item * sad_qty_per) as double) as ord_txn_curncy_amt,
  case
when costcentre.customcombo1='UnknownBL' then 'UNKNOWNBL' 
else upper(costcentre.customcombo1) 
end as product_line_code as prod_line_cd,
  cast(sad.sad_project as string) as proj_cd,
  upper(costcentre.costcentrecode) as cost_center_cd
  from sad_det sad
  inner join si_mstr si on lower(sad.sad_domain) = lower(si.si_domain)
  inner join sa_mstr sa on (lower(sa.sa_domain) = lower(sad.sad_domain) AND sa.sa_prefix = sad.sad_prefix AND sa.sa_nbr = sad.sad_nbr AND lower(sa.sa_site) = lower(si.si_site))
  left join Debtor d on d.debtorcode = sa.sa_cust --need sa to
  inner join left on d.debtortype_id = dt.DebtorType_ID --need sa to
  inner join d on d.businessrelation_id = bus.businessrelation_id --need sa to
  inner join d on (lower(sad.sad_domain) = lower(pt.pt_domain) AND sad.sad_for = pt.pt_part)
  left join pl_mstr pl on (lower(sad.sad_domain) = lower(pl.pl_domain) AND sad.sad_prodline = pl.pl_prod_line)
  left join ih_hist ih on (lower(sa.sa_domain) = lower(ih.ih_domain) AND sa.sa_cust = ih.ih_cust AND ih.ih_fsm_type = 'SC' and ih.ih_sa_nbr=sad.sad_nbr )
  left join idh_hist idh on (lower(idh.idh_domain) = lower(ih.ih_domain) AND idh.idh_inv_nbr = ih.ih_inv_nbr AND idh.idh_sa_nbr = sa.sa_nbr AND idh.idh_sad_line = sad.sad_line)
  left join ad_mstr ad on (ad.ad_addr = d.debtorcode AND ad.ad_domain = sad.sad_domain) -- 2018-06-26 CHG0037031
  where 1=1 and sad_end_date >= (current date - 6 months) and (sad.sad_line_type = '3' OR sad.sad_line_type = '5') and sad.sad_prefix <> 'Q' And sad_end_date >= current_timestamp and si.si_entity IN (‘3460', '4300', '4200’, '3100', '3120', '3420', '3110', '4100', '3130', '3850', '3200', '3204', '3240', '3245', '3250', '3255', '3265', '3270', '3275', '3280', '3300', '3520' ,'2100', '2110', '2120', '2130', '2700', 'czbr', 'STAT', 'ZEXT', '0', '0NL', '1Be', '1DK', '1Nl', '1No', '1SE', '2200', '2205', '2220', '2230', '2240', '2250', '2260', '2270', '2280', '2287', '2300', '2400', '2500', '2600', '2601', '2650', '2ES', '3AT', '3Ch', '2670', '2910') and AmountToInvoice <> InvoicedAmount
),

fact_daily_open_order_uiscall AS (
  select
  concat("msd_qad_",ca_mstr.ca_domain)||'|'||ETL Load Date YYYYMMDD||'|'||ca_mstr.ca_nbr||'|'||itm_det.itm_line||'|'|| as dly_open_ord_key,
  concat("msd_qad_",lower(ca_mstr.ca_domain)) as src_sys_cd,
  cast(null as decimal(38,0)) as as_of_dt_key,
  cast(ca_mstr.ca_nbr as string) as sls_ord_nbr,
  cast(null as string) as sls_ord_line_nbr,
  cast(null as string) as dw_src_cd,
  cast(null as string) as dw_dly_open_ord_key,
  cast(null as string) as src_crt_by,
  cast(ca_mstr.ca_opn_date as timestamp) as src_crt_ts,
  cast(ca_mstr.ca_mod_userid as string) as src_updt_by,
  cast(ca_mstr.ca_mod_date as timestamp) as src_updt_ts,
  current_timestamp as rec_crt_ts,
  current_timestamp as rec_updt_ts,
  concat('msd_qad_',lower(ca_mstr.ca_domain))||'|'||ca_mstr.ca_customer as bill_to_cust_key,
  upper(debtor.debtorcode) as bill_to_cust_id,
  cast(null as string) as bill_to_cust_nm,
  cast(null as double) as bo_co_curncy_amt,
  cast(null as string) as bo_flg,
  cast(null as double) as bo_lcur_amt,
  cast(null as double) as bo_qty,
  cast(null as string) as ccg_lcd_chnl,
  cast(null as string) as ccg_lcd_vndr_nbr,
  cast(null as string) as contact_key,
  cast(null as string) as co_usd_curncy_mth_rt_key,
  concat('msd_qad_',lower(si_mstr.si_domain))||'|'||si_mstr.si_entity as co_key,
  upper(si_mstr.si_entity) as co_cd,
  cast(null as string) as co_nm,
  cast(null as string) as co_curncy_cd,
  cast(null as string) as cur_lot_nbr,
  cast(null as string) as cust_po_nbr,
  cast(null as string) as derived_prod_key,
  cast(null as string) as derived_sku,
  cast(null as string) as derived_sku_nm,
  cast(null as decimal(38,0)) as expect_ship_dt_key,
  cast(null as double) as fin_bo_co_curncy_amt,
  cast(null as double) as fin_bo_lcur_amt,
  cast(null as double) as fin_bo_qty,
  cast(null as string) as fin_ord_line_complt_flg,
  cast(null as string) as hfm_entity_key,
  cast(null as string) as hfm_entity_cd,
  cast(null as double) as invc_qty,
  cast(null as decimal(38,0)) as mtl_avbl_dt_key,
  cast(null as double) as ord_co_curncy_amt,
  cast(ca_mstr.ca_curr as string) as ord_curncy_cd,
  cast(concat('msd_qad_',lower(ca_mstr.ca_domain))||'|'||ca_mstr.ca_opn_date as decimal(38,0)) as ord_dt_key,
  cast(null as string) as ord_hdr_usd_curncy_mth_rt_key,
  cast(null as double) as ord_lcur_amt,
  cast(null as string) as strg_loc_cd,
  cast(null as string) as req_strg_loc_cd,
  cast(null as decimal(38,0)) as ord_line_ship_nlt_dt_key,
  cast(null as double) as ord_qty,
  cast(null as decimal(38,0)) as orig_proms_dt_key,
  cast(null as string) as plant_key,
  cast(null as string) as plant_cd,
  cast(null as string) as plant_nm,
  concat('msd_qad_',itm_det.itm_domain)||'|'||itm_det.itm_part as prod_key,
  cast(null as string) as sku,
  cast(null as string) as sku_nm,
  cast(null as string) as prod_plant_key,
  cast(null as decimal(38,0)) as proms_delvr_dt_key,
  cast(null as decimal(38,0)) as req_delvr_dt_key,
  cast(null as string) as revnu_div,
  cast(null as decimal(38,0)) as ord_rls_dt_key,
  cast(null as double) as ship_qty,
  cast(null as string) as ship_to_cust_key,
  cast(ca_mstr.ca_eu_nbr as string) as ship_to_cust_id,
  cast(null as string) as ship_to_cust_nm,
  cast(null as string) as ship_to_cntry_hier_key,
  cast(null as string) as sls_ord_key,
  cast(null as string) as sold_to_cust_key,
  cast(null as string) as sold_to_cust_id,
  cast(null as string) as sold_to_cust_nm,
  cast(null as double) as target_qty,
  cast(null as double) as unit_std_cost,
  cast(null as string) as cur_ord_stat_cd,
  cast(null as string) as cur_ord_stat_nm,
  cast(null as string) as next_ord_stat_cd,
  cast(null as string) as next_ord_stat_nm,
  cast(null as string) as hdr_bill_block_cd,
  cast(null as string) as hdr_bill_block_nm,
  cast(null as string) as hdr_delvr_block_cd,
  cast(null as string) as hdr_delvr_block_nm,
  cast(null as string) as bill_block_cd,
  cast(null as string) as bill_block_nm,
  cast(null as string) as delvr_block_cd,
  cast(null as string) as delvr_block_nm,
  cast(null as string) as overall_stat_cd,
  cast(null as string) as overall_stat_nm,
  cast(null as string) as reject_rsn_cd,
  cast(null as string) as reject_rsn_nm,
  cast(null as string) as ord_type_cd,
  cast(null as string) as ord_type_nm,
  cast(null as string) as ord_overall_stat_cd,
  cast(null as string) as ord_overall_stat_nm,
  cast(null as string) as hdr_ord_type_cd,
  cast(null as string) as hdr_ord_type_nm,
  cast(null as string) as bo_stat_nm,
  cast(null as decimal(38,0)) as commit_dt_key,
  cast(null as decimal(38,0)) as proms_ship_dt_key,
  cast(null as decimal(38,0)) as sched_ship_dt_key,
  cast(null as string) as cust_key,
  cast(null as string) as sls_rep_cust_key,
  cast(null as string) as po_nbr,
  cast(null as string) as po_line_nbr,
  case
when lower(costcentre.customcombo0)='UnknownMD' then 'UNKNOWNMD' 
else  replace(replace(upper(costcentre.customlong0),'.',''),'_','') end as business_unit as bu_cd,
  cast(null as string) as sls_terr_cd,
  cast(null as string) as cost_curncy_cd,
  cast(null as string) as uom_cd,
  cast(Parts + LaborExpense:  (wod.wod_qty_req * wod.wod_price) - wod.wod_covered_amt  as 'parts',
(wr.wr_act_run * wr.wr_price) - wr.wr_covered_amt  as 'laborExpense'       need to add filter where parts + labor <> 0 as double) as prc_per_unit_amt,
  cast(Parts + LaborExpense:  (wod.wod_qty_req * wod.wod_price) - wod.wod_covered_amt  as 'parts',
(wr.wr_act_run * wr.wr_price) - wr.wr_covered_amt  as 'laborExpense'       need to add filter where parts + labor <> 0 as double) as ord_prc_per_unit_amt,
  cast(null as double) as disc_amt,
  cast(Parts + LaborExpense:  (wod.wod_qty_req * wod.wod_price) - wod.wod_covered_amt  as 'parts',
(wr.wr_act_run * wr.wr_price) - wr.wr_covered_amt  as 'laborExpense'       need to add filter where parts + labor <> 0 as double) as ord_txn_curncy_amt,
  case
when costcentre.customcombo1='UnknownBL' then 'UNKNOWNBL' 
else upper(costcentre.customcombo1) 
end as product_line_code as prod_line_cd,
  cast(null as string) as proj_cd,
  upper(costcentre.costcentrecode) as cost_center_cd
  from ca_mstr
),

fact_daily_open_order_oo_rma AS (
  select
  Dly_open_ord_key: concat("msd_qad_",lower(so_mstr.so_domain))||'|'||ETL Load Date YYYYMMDD||'|'||so_mstr.so_nbr||'|'||sod_det.sod_line||'|'|| Coalesce(idh_hist.idh_part, sod_det.sod_part) as dly_open_ord_key,
  concat("msd_qad_",lower(so_mstr.so_domain))||'|'||so_mstr.so_cust as src_sys_cd,
  cast(null as decimal(38,0)) as as_of_dt_key,
  cast(so.so_nbr as string) as sls_ord_nbr,
  cast(sod.sod_line as string) as sls_ord_line_nbr,
  cast(null as string) as dw_src_cd,
  cast(null as string) as dw_dly_open_ord_key,
  cast(null as string) as src_crt_by,
  cast(so.so_ord_date as timestamp) as src_crt_ts,
  cast(null as string) as src_updt_by,
  cast(null as timestamp) as src_updt_ts,
  current_timestamp as rec_crt_ts,
  current_timestamp as rec_updt_ts,
  concat("msd_qad_",lower(so_mstr.so_domain))||'|'||so_mstr.so_bill as bill_to_cust_key,
  cast(so.so_bill as string) as bill_to_cust_id,
  cast(bus.businessrelationsearchname as string) as bill_to_cust_nm,
  cast(null as double) as bo_co_curncy_amt,
  cast(null as string) as bo_flg,
  cast(null as double) as bo_lcur_amt,
  cast(null as double) as bo_qty,
  cast(null as string) as ccg_lcd_chnl,
  cast(null as string) as ccg_lcd_vndr_nbr,
  cast(null as string) as contact_key,
  cast(null as string) as co_usd_curncy_mth_rt_key,
  concat('msd_qad_', lower(si_mstr.si_domain) )||'|'||si_mstr.si_entity as co_key,
  cast(si.si_entity as string) as co_cd,
  cast(si.si_desc as string) as co_nm,
  cast(null as string) as co_curncy_cd,
  cast(null as string) as cur_lot_nbr,
  cast(null as string) as cust_po_nbr,
  cast(null as string) as derived_prod_key,
  cast(null as string) as derived_sku,
  cast(null as string) as derived_sku_nm,
  cast(null as decimal(38,0)) as expect_ship_dt_key,
  cast(null as double) as fin_bo_co_curncy_amt,
  cast(null as double) as fin_bo_lcur_amt,
  cast(null as double) as fin_bo_qty,
  cast(null as string) as fin_ord_line_complt_flg,
  cast(null as string) as hfm_entity_key,
  cast(null as string) as hfm_entity_cd,
  cast(null as double) as invc_qty,
  cast(null as decimal(38,0)) as mtl_avbl_dt_key,
  cast(null as double) as ord_co_curncy_amt,
  cast(so.so_curr as string) as ord_curncy_cd,
  cast(concat('msd_qad_',lower(ca_mstr.ca_domain))||'|'||so.so_ord_date as decimal(38,0)) as ord_dt_key,
  cast(null as string) as ord_hdr_usd_curncy_mth_rt_key,
  cast(null as double) as ord_lcur_amt,
  cast(null as string) as strg_loc_cd,
  cast(null as string) as req_strg_loc_cd,
  cast(null as decimal(38,0)) as ord_line_ship_nlt_dt_key,
  cast(case when idh.idh_qty_ord is null then cast(sod_det.sod_qty_ord - sod_det.sod_qty_inv) as double) else cast(idh.idh_qty_ord end as double) as quantity, as double) as ord_qty,
  cast(null as decimal(38,0)) as orig_proms_dt_key,
  cast(null as string) as plant_key,
  cast(null as string) as plant_cd,
  cast(null as string) as plant_nm,
  concat('msd_qad_',lower(sod_det.sod_domain) )||'|'||sod_det.sod_part as prod_key,
  Coalesce(idh_hist.idh_part, sod_det.sod_part) as sku,
  cast(pt.pt_desc1 as string) as sku_nm,
  cast(null as string) as prod_plant_key,
  cast(null as decimal(38,0)) as proms_delvr_dt_key,
  cast(null as decimal(38,0)) as req_delvr_dt_key,
  cast(null as string) as revnu_div,
  cast(null as decimal(38,0)) as ord_rls_dt_key,
  cast(null as double) as ship_qty,
  cast(null as string) as ship_to_cust_key,
  cast(so.so_ship as string) as ship_to_cust_id,
  cast(null as string) as ship_to_cust_nm,
  cast(null as string) as ship_to_cntry_hier_key,
  cast(null as string) as sls_ord_key,
  cast(null as string) as sold_to_cust_key,
  cast(null as string) as sold_to_cust_id,
  cast(null as string) as sold_to_cust_nm,
  cast(null as double) as target_qty,
  cast(null as double) as unit_std_cost,
  cast(null as string) as cur_ord_stat_cd,
  cast(null as string) as cur_ord_stat_nm,
  cast(null as string) as next_ord_stat_cd,
  cast(null as string) as next_ord_stat_nm,
  cast(null as string) as hdr_bill_block_cd,
  cast(null as string) as hdr_bill_block_nm,
  cast(null as string) as hdr_delvr_block_cd,
  cast(null as string) as hdr_delvr_block_nm,
  cast(null as string) as bill_block_cd,
  cast(null as string) as bill_block_nm,
  cast(null as string) as delvr_block_cd,
  cast(null as string) as delvr_block_nm,
  cast(null as string) as overall_stat_cd,
  cast(null as string) as overall_stat_nm,
  cast(null as string) as reject_rsn_cd,
  cast(null as string) as reject_rsn_nm,
  cast(null as string) as ord_type_cd,
  case when so_mstr.so_fsm_type = 'RMA' then 'RMA' 
		else 'SO'
		end as "OrderType" as ord_type_nm,
  cast(null as string) as ord_overall_stat_cd,
  cast(null as string) as ord_overall_stat_nm,
  cast(null as string) as hdr_ord_type_cd,
  cast(null as string) as hdr_ord_type_nm,
  cast(null as string) as bo_stat_nm,
  cast(null as decimal(38,0)) as commit_dt_key,
  cast(null as decimal(38,0)) as proms_ship_dt_key,
  cast(null as decimal(38,0)) as sched_ship_dt_key,
  cast(null as string) as cust_key,
  cast(null as string) as sls_rep_cust_key,
  cast(null as string) as po_nbr,
  cast(null as string) as po_line_nbr,
  case
when lower(costcentre.customcombo0)='unknownmd' then 'UNKNOWNMD' 
else  replace(replace(upper(costcentre.customlong0),'.',''),'_','') end as business_unit as bu_cd,
  cast(null as string) as sls_terr_cd,
  cast(null as string) as cost_curncy_cd,
  cast(IDH.idh_um as string) as uom_cd,
  cast(sod.sod_price as double) as prc_per_unit_amt,
  cast(sod.sod_price as double) as ord_prc_per_unit_amt,
  cast(null as double) as disc_amt,
  cast(case when rhd.rhd_price is null then (sod_det.sod_price*(sod_det.sod_qty_ord - sod_det.sod_qty_inv)) else rhd.rhd_price end as ord_txn_curncy_amt, as double) as ord_txn_curncy_amt,
  case 
when coalesce(idh.idh_prodline,'') <> '' then idh.idh_prodline
when coalesce(rhd.rhd_prodline,'') <> '' then rhd.rhd_prodline
else '' end as prod_line_cd,
  cast(null as string) as proj_cd,
  upper(costcentre.costcentrecode) as cost_center_cd
  from so_mstr so
  inner join sod_det sod on lower(so.so_domain) = lower(sod.sod_domain) and so.so_nbr = sod.sod_nbr AND sod.sod_qty_ord <> sod.sod_qty_inv AND sod.sod_price <> 0
  left join si_mstr si on (lower(si.si_domain) = lower(so.so_domain) AND lower(si.si_site) = lower(so.so_site))
  left join pt_mstr pt on lower(sod.sod_domain) = lower(pt.pt_domain) and sod.sod_part = pt.pt_part
  left join xxpt_mstr xxpt on lower(pt.pt_domain) = lower(xxpt.xxpt_domain) and pt.pt_part = xxpt.xxpt_part
  left join ad_mstr ad on lower(so.so_domain) = lower(ad.ad_domain) and so.so_cust = ad.ad_addr
  left join pl_mstr pl on lower ( pt.pt_domain) = lower(pl.pl_domain) and pt.pt_prod_line = pl.pl_prod_line
  left join Debtor d on d.debtorcode = so.so_cust
  left join debtorType dt on d.debtortype_id = dt.DebtorType_ID
  left join BusinessRelation bus on d.businessrelation_id = bus.businessrelation_id
  left join idh_hist IDH on (idh.idh_domain = sod.sod_domain AND trim(idh.idh_nbr) = trim(so.so_nbr) AND idh.idh_line = sod.sod_line)
  where 1=1 and si.si_entity IN ((‘3460', '4300', '4200’, '3100', '3120', '3420', '3110', '4100', '3130', '3850', '3200', '3204', '3240', '3245', '3250', '3255', '3265', '3270', '3275', '3280', '3300', '3520','2100', '2110', '2120', '2130', '2700', 'czbr', 'STAT', 'ZEXT', '0', '0NL', '1Be', '1DK', '1Nl', '1No', '1SE', '2200', '2205', '2220', '2230', '2240', '2250', '2260', '2270', '2280', '2287', '2300', '2400', '2500', '2600', '2601', '2650', '2ES', '3AT', '3Ch', '2670', '2910') and (so.so_fsm_type = '' or so_fsm_type = 'RMA') need to apply a filter to only return the maximum updt_dt for so_nbr from so_mstr something like (where updt_dt=MAX(updt_dt) for so_nbr)
),

f_dly_open_order_all AS (
  SELECT * FROM fact_daily_open_order_uisc
  UNION ALL
  SELECT * FROM fact_daily_open_order_uiscall
  UNION ALL
  SELECT * FROM fact_daily_open_order_oo_rma
)

SELECT
  dly_open_ord_key,
  src_sys_cd,
  as_of_dt_key,
  sls_ord_nbr,
  sls_ord_line_nbr,
  dw_src_cd,
  dw_dly_open_ord_key,
  src_crt_by,
  src_crt_ts,
  src_updt_by,
  src_updt_ts,
  rec_crt_ts,
  rec_updt_ts,
  bill_to_cust_key,
  bill_to_cust_id,
  bill_to_cust_nm,
  bo_co_curncy_amt,
  bo_flg,
  bo_lcur_amt,
  bo_qty,
  ccg_lcd_chnl,
  ccg_lcd_vndr_nbr,
  contact_key,
  co_usd_curncy_mth_rt_key,
  co_key,
  co_cd,
  co_nm,
  co_curncy_cd,
  cur_lot_nbr,
  cust_po_nbr,
  derived_prod_key,
  derived_sku,
  derived_sku_nm,
  expect_ship_dt_key,
  fin_bo_co_curncy_amt,
  fin_bo_lcur_amt,
  fin_bo_qty,
  fin_ord_line_complt_flg,
  hfm_entity_key,
  hfm_entity_cd,
  invc_qty,
  mtl_avbl_dt_key,
  ord_co_curncy_amt,
  ord_curncy_cd,
  ord_dt_key,
  ord_hdr_usd_curncy_mth_rt_key,
  ord_lcur_amt,
  strg_loc_cd,
  req_strg_loc_cd,
  ord_line_ship_nlt_dt_key,
  ord_qty,
  orig_proms_dt_key,
  plant_key,
  plant_cd,
  plant_nm,
  prod_key,
  sku,
  sku_nm,
  prod_plant_key,
  proms_delvr_dt_key,
  req_delvr_dt_key,
  revnu_div,
  ord_rls_dt_key,
  ship_qty,
  ship_to_cust_key,
  ship_to_cust_id,
  ship_to_cust_nm,
  ship_to_cntry_hier_key,
  sls_ord_key,
  sold_to_cust_key,
  sold_to_cust_id,
  sold_to_cust_nm,
  target_qty,
  unit_std_cost,
  cur_ord_stat_cd,
  cur_ord_stat_nm,
  next_ord_stat_cd,
  next_ord_stat_nm,
  hdr_bill_block_cd,
  hdr_bill_block_nm,
  hdr_delvr_block_cd,
  hdr_delvr_block_nm,
  bill_block_cd,
  bill_block_nm,
  delvr_block_cd,
  delvr_block_nm,
  overall_stat_cd,
  overall_stat_nm,
  reject_rsn_cd,
  reject_rsn_nm,
  ord_type_cd,
  ord_type_nm,
  ord_overall_stat_cd,
  ord_overall_stat_nm,
  hdr_ord_type_cd,
  hdr_ord_type_nm,
  bo_stat_nm,
  commit_dt_key,
  proms_ship_dt_key,
  sched_ship_dt_key,
  cust_key,
  sls_rep_cust_key,
  po_nbr,
  po_line_nbr,
  bu_cd,
  sls_terr_cd,
  cost_curncy_cd,
  uom_cd,
  prc_per_unit_amt,
  ord_prc_per_unit_amt,
  disc_amt,
  ord_txn_curncy_amt,
  prod_line_cd,
  proj_cd,
  cost_center_cd
FROM f_dly_open_order_all;